### ISSUE TITLE
With enabled phrase I18n.t method should return String object

### ISSUE THREAD

**Issue by jjustaments** [phrase/phrase#50]
If we call String methods on Phrase::Delegate::I18n object the result will be unexpected.
Example from rails console:
```
2.1.1 :001 > Phrase.enabled = true
 => true
2.1.1 :002 > a = I18n.t('hello')
 => "{{__phrase_hello__}}"
2.1.1 :003 > b = a.upcase
 => "{{__PHRASE_HELLO__}}"
2.1.1 :004 > b.to_s
 => "{{__phrase___}}"
```

Small fix can solve this problem:
```
class Phrase::Backend::PhraseService
  def translate(*args)
    if to_be_translated_without_phrase?(args)
      I18n.translate_without_phrase(*args)
    else
      phrase_delegate_for(args).to_s
    end
  end
end
```

**Comment by docstun** [comment]
We'll look into this asap.

**Comment by docstun** [comment]
@jjustaments sorry for the delay: I think I understand the problem but the fix won't solve the problem sufficiently. We cannot call #to_s on all keys since some of them behave like arrays or hashes rather than strings. Any other solution for this that comes to your mind? 

By the way: I would not use #upcase for text, a CSS-based solution is usually way better.

**Comment by jjustaments** [comment]
I think it is possible to check key value type and if it is String, than call #to_s
I will close the issue, because my fix works perfectly for our application.

**Comment by docstun** [comment]
Thanks :)
